project:
  type: website
  output-dir: docs

website:
  title: "Ameen's Personal Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CorporalCupcake/AmeenPersonalBlog
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cyborg
    # css: styles.css

execute:
  engine: knitr  # Specifies the execution engine for R code
