project:
  type: website
  output-dir: docs

website:
  title: "AmeenPersonalBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CorporalCupcake/AmeenPersonalBlog
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css



